[bumpver]
version_pattern = "MAJOR.MINOR.PATCH"
current_version = "1.0.1"
commit_message = "bump version {old_version} → {new_version}"
tag_message = "Release v{new_version}"
tag_scope = "default"
tag_format = "v{version}"
commit = true
tag = true
push = true
allow_dirty = false

[bumpver.file_patterns]
"pyproject.toml" = [
  'version = "{version}"',
]
"src/pygsk/__init__.py" = [
  '__version__ = "{version}"',
]
"CITATION.cff" = [
  'version: {version}  # bumpver',
]

".zenodo.json" = [
  '"version": "{version}"',
]


