[tool.bumpver]
version_pattern = "MAJOR.MINOR.PATCH"
current_version = "1.0.3"

commit_message = "bump: release v{new_version}"
tag_message    = "Release v{new_version}"

# Create v-prefixed tags
tag_name  = "v{new_version}"
# Recognize v-prefixed tags (so “Latest version from VCS tag” picks them up)
tag_regex = "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"

commit = true
tag    = true
push   = true
allow_dirty = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['version = "{version}"']
"src/pygsk/__init__.py" = ['__version__ = "{version}"']
"CITATION.cff" = ['version: {version}  # bumpver']
".zenodo.json" = ['"version": "{version}"']
