[tool.bumpver]
version_pattern = "MAJOR.MINOR.PATCH"
current_version = "1.0.12"

commit_message = "bump: release v{new_version}"
tag_message    = "Release v{new_version}"

# Use tag_format for maximum compatibility
tag_format = "v{version}"
# Ensure only v-prefixed tags are considered “latest”
tag_regex  = "^v(?P<version>\\d+\\.\\d+\\.\\d+)$"

commit = true
tag    = true
push   = true
allow_dirty = false

[tool.bumpver.file_patterns]
"pyproject.toml"       = ['version = "{version}"']
"src/pygsk/__init__.py"= ['__version__ = "{version}"']
"CITATION.cff"         = ['version: {version}  # bumpver']
".zenodo.json"         = ['"version": "{version}"']
