[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyGSK"
version = "0.1.0"
description = "Generalized Spectral Kurtosis Toolkit"
authors = [{ name = "Gelu" }]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pytest"
]