[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyGSK"
version = "0.1.0"
description = "Generalized Spectral Kurtosis Toolkit"
authors = [
    { name = "Gelu M. Nita" }
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "MIT"}
dependencies = [
    "numpy",
    "scipy",
    "matplotlib"
]

[tool.setuptools.packages.find]
include = ["pyGSK", "cli"]

[project.optional-dependencies]
dev = [
    "pytest",
    "build",
    "twine"
]

[project.urls]
"Homepage" = "https://github.com/SUNCAST-org/pyGSK"
"Source" = "https://github.com/SUNCAST-org/pyGSK"
"Bug Tracker" = "https://github.com/SUNCAST-org/pyGSK/issues"